name: auto_refresh_on_reconnect
description: A lightweight Flutter package that automatically refreshes widgets when internet connection is restored.
version: 0.1.0
homepage: https://github.com/Sourav-Sonkar/auto_refresh_on_reconnect
repository: https://github.com/Sourav-Sonkar/auto_refresh_on_reconnect
issue_tracker: https://github.com/Sourav-Sonkar/auto_refresh_on_reconnect/issues
documentation: https://github.com/Sourav-Sonkar/auto_refresh_on_reconnect/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
